"""Generate exportable opposition scouting briefs."""

from __future__ import annotations

import pandas as pd
from sqlalchemy.engine import Engine

from src.metrics import (
    final_third_entries,
    league_ppda_ranking,
    ppda_summary,
    xg_season_totals,
    xg_summary,
    zone_summary,
)
from src.set_pieces import (
    CORNER_PATTERN,
    attack_summary,
    defense_summary,
    delivery_players,
    delivery_zone,
    get_deliveries,
    shot_players,
)


def build_opposition_brief(team: str, engine: Engine) -> str:
    xg_totals = xg_season_totals(engine, team)
    xg_breakdown = xg_summary(engine, team)
    zone_df = zone_summary(engine, team)
    entries_df = final_third_entries(engine, team)
    ppda = ppda_summary(engine, team)
    ppda_rank = league_ppda_ranking(engine)
    team_rank = ppda_rank[ppda_rank["team"] == team].iloc[0]

    attack_df = attack_summary(engine, team)
    defense_df = defense_summary(engine, team)
    corner_takers = delivery_players(engine, team, "Corner")
    corner_shooters = shot_players(engine, team, CORNER_PATTERN)
    corner_deliveries = get_deliveries(engine, team, "Corner")
    zone_targets = delivery_zone(corner_deliveries, "end_location_x", "end_location_y")

    strongest_zone = zone_df.sort_values("total_xg", ascending=False).iloc[0]
    top_entry_zone = entries_df.sort_values("entries", ascending=False).iloc[0]
    corners = attack_df[attack_df["context"] == "Corners (shots)"].iloc[0]
    free_kicks = attack_df[attack_df["context"] == "Free kicks (shots)"].iloc[0]
    conceded_all = defense_df[defense_df["context"] == "All set pieces conceded"].iloc[0]

    lines = [
        f"# Opposition Scouting Brief: {team}",
        "Premier League 2015/2016 | Generated by Soccer Scouting Platform",
        "",
        "---",
        "",
        "## Executive Summary",
        f"{team} created {xg_totals['total_xg']:.2f} xG from {xg_totals['shots']} shots and scored "
        f"{xg_totals['goals']} goals ({xg_totals['xg_difference']:+.2f} xG difference). "
        f"Their PPDA of {ppda['ppda']} ranks {int(team_rank['press_rank'])} of {len(ppda_rank)} "
        f"(lower = more aggressive press). Set-piece defense is a key vulnerability: "
        f"{int(conceded_all['goals'])} goals conceded from set pieces.",
        "",
        "## 1. Chance Quality & Finishing",
        f"- Total xG: {xg_totals['total_xg']}",
        f"- Goals scored: {xg_totals['goals']}",
        f"- Average xG per shot: {xg_totals['avg_xg_per_shot']}",
        "",
        "### Shot context",
    ]

    for _, row in xg_breakdown.iterrows():
        context = row["shot_context"] if pd.notna(row["shot_context"]) else "Unknown"
        lines.append(
            f"- **{context}:** {int(row['shots'])} shots, {row['total_xg']:.2f} xG, {int(row['goals'])} goals"
        )

    lines.extend(
        [
            "",
            "## 2. Pressing & Build-Up",
            f"- **PPDA:** {ppda['ppda']} (league rank {int(team_rank['press_rank'])})",
            f"- **Strongest shooting zone:** {strongest_zone['zone']} ({strongest_zone['total_xg']:.2f} xG)",
            f"- **Primary build-up channel:** {top_entry_zone['zone']} ({int(top_entry_zone['entries'])} final-third entries)",
            "",
            "### Recommended approach",
            "- If PPDA is low: expect aggressive pressing; use quick vertical passes to bypass midfield.",
            "- If PPDA is high: expect a deeper block; commit fullbacks higher and overload wide zones.",
            "",
            "## 3. Set Pieces",
            f"- **Corners taken:** {int(corners['deliveries'])} → {int(corners['shots'])} shots, "
            f"{corners['total_xg']:.2f} xG, {int(corners['goals'])} goals",
            f"- **Free-kick shots:** {int(free_kicks['shots'])} → {free_kicks['total_xg']:.2f} xG, "
            f"{int(free_kicks['goals'])} goals",
            f"- **Set pieces conceded:** {int(conceded_all['shots'])} shots, "
            f"{conceded_all['total_xg']:.2f} xG, {int(conceded_all['goals'])} goals",
        ]
    )

    if not corner_takers.empty:
        top_taker = corner_takers.iloc[0]
        lines.append(
            f"- **Primary corner taker:** {top_taker['player_name']} ({int(top_taker['deliveries'])} corners)"
        )

    if not zone_targets.empty:
        top_zone = zone_targets.sort_values("count", ascending=False).iloc[0]
        lines.append(f"- **Preferred corner target zone:** {top_zone['target_zone']}")

    lines.append("")
    lines.append("### Mark these players on corners")
    if corner_shooters.empty:
        lines.append("- No corner-shot threats identified.")
    else:
        for _, row in corner_shooters.head(5).iterrows():
            lines.append(
                f"- {row['player_name']}: {int(row['shots'])} shots, {row['total_xg']:.2f} xG"
            )

    lines.extend(
        [
            "",
            "## 4. Match-Day Checklist",
            "- [ ] Assign dedicated marker to primary corner taker",
            "- [ ] Organize zonal marking for top aerial threats",
            "- [ ] Exploit set-piece defensive vulnerability on our attacking restarts",
            "- [ ] Adjust build-up tempo based on PPDA profile",
            f"- [ ] Shade defenders toward {strongest_zone['zone']} shooting zone",
            "",
            "---",
            "*Data source: StatsBomb Open Data*",
        ]
    )

    return "\n".join(lines)